# Generated by Django 4.1.3 on 2022-12-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreciosTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corte', models.CharField(max_length=100, verbose_name='Corte')),
                ('precio', models.CharField(max_length=100, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'corte',
                'verbose_name_plural': 'cortes',
                'ordering': ['corte'],
            },
        ),
    ]
