# Generated by Django 4.1.3 on 2022-12-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.CharField(max_length=100, verbose_name='Oferta')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'oferta',
                'verbose_name_plural': 'ofertas',
                'ordering': ['oferta'],
            },
        ),
    ]
