# Generated by Django 4.1.3 on 2023-01-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100, verbose_name='Servicio')),
                ('estilista', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estilista')),
                ('dia', models.DateField(verbose_name='Día')),
                ('hore', models.TimeField(verbose_name='Hora')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('descripcion', models.TextField(max_length=200, verbose_name='Descripción')),
            ],
        ),
    ]
