# Generated by Django 4.1.3 on 2023-01-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='hore',
            new_name='hora',
        ),
    ]
