# Generated by Django 4.1.3 on 2023-01-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cantidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cantidad'),
        ),
    ]
